### ISSUE TITLE
[BUG] NonTensorSpec calls NonTensorData with unexpected shape argument

### ISSUE THREAD

**Issue by maichmueller** [pytorch/rl#2168]
## Describe the bug

a NonTensorSpec apparently instantiates a NonTensorData object wrong on calls such as `one`, `zero`, and `rand`.

## To Reproduce

```python
import torchrl

torchrl.data.NonTensorSpec().one(shape=[1])
```
shows 

```bash
Traceback (most recent call last):
  File "/work/rleap1/michael.aichmueller/miniconda/envs/rgnn/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-23-02439521e062>", line 1, in <module>
    torchrl.data.NonTensorSpec().one(shape=[1])
  File "/work/rleap1/michael.aichmueller/miniconda/envs/rgnn/lib/python3.11/site-packages/torchrl/data/tensor_specs.py", line 1953, in one
    return NonTensorData(data=None, shape=self.shape, device=self.device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/rleap1/michael.aichmueller/miniconda/envs/rgnn/lib/python3.11/site-packages/tensordict/tensorclass.py", line 389, in wrapper
    init(self, **kwargs)
TypeError: NonTensorData.__init__() got an unexpected keyword argument 'shape'
```

This currently comes up when I try to build an env with a `NonTensorSpec` and run `check_env_specs(env)` on it.

## Expected behavior

Not throwing an error.

## System info

Describe the characteristic of your environment:
 * Describe how the library was installed: pip
 * Python version: 3.11.8
 * Ubuntu 22.04

```python
import torchrl, numpy, sys

print(torchrl.__version__, numpy.__version__, sys.version, sys.platform)
0.4.0 1.26.4 3.11.8 (main, Feb 26 2024, 21:39:34) [GCC 11.2.0] linux
```

## Reason and Possible fixes

These lines seem to be at fault:

```python
class NonTensorSpec(TensorSpec):
    """A spec for non-tensor data."""
...
    def rand(self, shape):
        return NonTensorData(data=None, shape=self.shape, device=self.device)

    def zero(self, shape):
        return NonTensorData(data=None, shape=self.shape, device=self.device)

    def one(self, shape):
        return NonTensorData(data=None, shape=self.shape, device=self.device)
```

## Checklist

- [X] I have checked that there is no similar issue in the repo (**required**)
- [X] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [X] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
Oh yeah that should be batch_size!
let me fix those

**Comment by vmoens** [comment]
This is already fixed on main
https://github.com/pytorch/rl/blob/eaa3dd8c895d310e406045662ba70300d9c9d4d6/torchrl/data/tensor_specs.py#L1952-L1959
I can add the test though

**Comment by c3-utsavdutta98** [comment]
@vmoens , thanks for your help on this^, ran into the same issue, am on the main branch now and still running into an issue.

For a bit of context, my ._step(), generates a td with a field "x", in my custom env.

"x" is itself a tensordict with a nested key structure, where the keys are not fixed (variable depending on the env).

I was trying a super simple observation spec with a blank NonTensorSpec:
```
self.observation_spec = CompositeSpec(
            updated_demand=NonTensorSpec(shape=(batch_size,)),
            shape=(batch_size, )
        )
```

And when instantiating the SyncDataCollector I eventually run into :

<img width="815" alt="image" src="https://github.com/pytorch/rl/assets/107651369/e4fb6857-2858-432f-ac38-81394c3a4ea5">

Just want to confirm this is a different issue.

**Comment by vmoens** [comment]
Interesting, that seems to be an issue with NonTensorData which receives smth unexpected during `update`.

I ran this code and it works fine on my end (on main branch), can you help me figure out how your example differs?

```python
from torchrl.envs import GymEnv, Transform, check_env_specs
from torchrl.data import NonTensorSpec, TensorSpec
from torchrl.collectors import SyncDataCollector
from tensordict import TensorDictBase, TensorDict, NonTensorData

class AddNontTensorData(Transform):
    def _call(self, tensordict: TensorDictBase) -> TensorDictBase:
        tensordict["nt"] = "a string!"
        return tensordict

    def _reset(
        self, tensordict: TensorDictBase, tensordict_reset: TensorDictBase
    ) -> TensorDictBase:
        return tensordict_reset.set("nt", NonTensorData("reset!"))

    def transform_observation_spec(self, observation_spec: TensorSpec) -> TensorSpec:
        observation_spec["nt"] = NonTensorSpec(shape=())
        return observation_spec

env = GymEnv("CartPole-v1").append_transform(AddNontTensorData())
print(env.rollout(3))
check_env_specs(env)

collector = SyncDataCollector(env, frames_per_batch=200)
for data in collector:
    print(data)
    break
```
